name: Tests

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Query database
        run: |
          psql -d postgres://postgres:123456@postgres:5432 -c 'CREATE DATABASE app;'
          psql -d postgres://postgres:123456@postgres:5432/app < database/create.sql
      - name: Install dependencies
        run: npm ci
      - run: npm test

